### ISSUE TITLE
not working with a1111 1.9-rc dev bruch

### ISSUE THREAD

**Issue by githabtane** [adieyal/sd-dynamic-prompts#754]
*** Error running process: E:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI19RC\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
    Traceback (most recent call last):
      File "E:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI19RC\modules\scripts.py", line 820, in process
        script.process(p, *script_args)
      File "E:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI19RC\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py", line 372, in process
        ignore_whitespace = opts.dp_ignore_whitespace
      File "E:\StabilityMatrix\Data\Packages\Stable Diffusion WebUI19RC\modules\options.py", line 142, in __getattr__
        return super(Options, self).__getattribute__(item)
    AttributeError: 'Options' object has no attribute 'dp_ignore_whitespace'

It doesn't show up in the settings tab

**Comment by Baysul** [comment]
Yep. I'm getting the exact same error on the dev branch. Not sure if this issue will be addressed until after the release is finalized though.

**Comment by akx** [comment]
Right, confirmed this is a bug with fresh installs. Will look into it.

**Comment by akx** [comment]
@githabtane Can you pull the newest `main` and retry?

**Comment by githabtane** [comment]
I got the latest version of this extension and tried again and it worked fine

**Comment by akx** [comment]
Closing as fixed, then!
